config-version: 2
name: 'salesforce'
version: '0.5.1'
require-dbt-version: [">=1.0.0", "<2.0.0"]
models:
  salesforce:
    materialized: table
    intermediate:
      materialized: ephemeral
vars:
  salesforce:
    account: "{{ ref('stg_salesforce__account') }}"
    opportunity: "{{ ref('stg_salesforce__opportunity') }}"
    user: "{{ ref('stg_salesforce__user') }}"
    user_role: "{{ ref('stg_salesforce__user_role') }}"
    opportunity_enhanced_pass_through_columns: []
clean-targets:
- target
- dbt_modules
- dbt_packages
