config-version: 2
name: 'salesforce'
version: '1.2.0'
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  salesforce:
    materialized: table
    intermediate:
      materialized: ephemeral

vars:
  salesforce:
    account: "{{ ref('stg_salesforce__account') }}"
    opportunity: "{{ ref('stg_salesforce__opportunity') }}"
    user: "{{ ref('stg_salesforce__user') }}"
    user_role: "{{ ref('stg_salesforce__user_role') }}"
    contact: "{{ ref('stg_salesforce__contact') }}"
    lead: "{{ ref('stg_salesforce__lead') }}"
    task: "{{ ref('stg_salesforce__task') }}"
    event: "{{ ref('stg_salesforce__event') }}"
    product_2: "{{ ref('stg_salesforce__product_2') }}"
    order: "{{ ref('stg_salesforce__order') }}"
    opportunity_line_item: "{{ ref('stg_salesforce__opportunity_line_item') }}"

    account_history: "{{ ref('stg_salesforce__account_history') }}"
    contact_history: "{{ ref('stg_salesforce__contact_history') }}"
    opportunity_history: "{{ ref('stg_salesforce__opportunity_history') }}"
    
    salesforce__account_pass_through_columns: []
    salesforce__contact_pass_through_columns: []
    salesforce__event_pass_through_columns: []
    salesforce__lead_pass_through_columns: []
    salesforce__opportunity_pass_through_columns: []
    salesforce__opportunity_line_item_pass_through_columns: []
    salesforce__order_pass_through_columns: []
    salesforce__product_2_pass_through_columns: []
    salesforce__task_pass_through_columns: []
    salesforce__user_role_pass_through_columns: []
    salesforce__user_pass_through_columns: []

clean-targets:
- target
- dbt_modules
- dbt_packages