config-version: 2
name: 'salesforce'
version: '2.0.0'
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  salesforce:
    +persist_docs:
      relation: true
      columns: true
    +materialized: table
    intermediate:
      +materialized: ephemeral
    salesforce:
      staging:
        +materialized: table
    salesforce_history:
      staging:
        +materialized: table

vars:
  salesforce:
    account: "{{ source('salesforce', 'account') }}"
    opportunity: "{{ source('salesforce', 'opportunity') }}"
    user: "{{ source('salesforce', 'user') }}"
    user_role: "{{ source('salesforce', 'user_role') }}"
    contact: "{{ source('salesforce', 'contact') }}"
    lead: "{{ source('salesforce', 'lead') }}"
    task: "{{ source('salesforce', 'task') }}"
    event: "{{ source('salesforce', 'event') }}"
    product_2: "{{ source('salesforce', 'product_2') }}"
    order: "{{ source('salesforce', 'order') }}"
    opportunity_line_item: "{{ source('salesforce', 'opportunity_line_item') }}"

    account_history: "{{ source('salesforce_history', 'account') }}"
    contact_history: "{{ source('salesforce_history', 'contact') }}"
    opportunity_history: "{{ source('salesforce_history', 'opportunity') }}"

    
    salesforce__account_pass_through_columns: []
    salesforce__contact_pass_through_columns: []
    salesforce__event_pass_through_columns: []
    salesforce__lead_pass_through_columns: []
    salesforce__opportunity_pass_through_columns: []
    salesforce__opportunity_line_item_pass_through_columns: []
    salesforce__order_pass_through_columns: []
    salesforce__product_2_pass_through_columns: []
    salesforce__task_pass_through_columns: []
    salesforce__user_role_pass_through_columns: []
    salesforce__user_pass_through_columns: []

clean-targets:
- target
- dbt_modules
- dbt_packages
