name: 'salesforce_integration_tests'
version: '1.0.0'
config-version: 2

profile: 'integration_tests'

vars:

  salesforce_source:
    salesforce_account_identifier: "account_data"
    salesforce_opportunity_identifier: "opportunity_data"
    salesforce_user_identifier: "user_data"
    salesforce_user_role_identifier: "user_role_data"
    salesforce_schema: salesforce_source_integration_tests_1

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
    
seeds:
  salesforce_integration_tests:
    +column_types:
      _fivetran_synced: timestamp
      _fivetran_active: boolean
    account_data:
      +column_types:
        last_activity_date: timestamp
        last_referenced_date: timestamp
        last_viewed_date: timestamp
        annual_revenue: float
        billing_latitude: float
        billing_longitude: float
        shipping_latitude: float
        shipping_longitude: float
    opportunity_data:
      +column_types:
        close_date: timestamp
        created_date: timestamp
        last_activity_date: timestamp
        last_referenced_date: timestamp
        last_viewed_date: timestamp
        amount: float
        probability: float
    user_data:
      +column_types:
        last_login_date: timestamp
        last_referenced_date: timestamp
        last_viewed_date: timestamp
        offline_trial_expiration_date: timestamp
        latitude: float
        longitude: float

clean-targets:
    - target
    - dbt_modules